#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# sudo not required for some system commands
for command in mount umount pacman shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command


# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	mkdir="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner" \
	sc="sc-im"

# Colorize commands when possible.
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	z="zathura" \
	c="clear" \
	g="git" \
    config="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME" \

# cd
alias \
	".."="cd .." \
	"..."="cd ../.." \
	"...."="cd ../../.." \
	"....."="cd ../../../.." \
	"dockervol"="cd /var/lib/docker/volumes" \
	prev='cd ../"$(ls -F .. | grep '/' | grep -B1 -xF "${PWD##*/}/" | head -n 1)"' \
	next='cd ../"$(ls -F .. | grep '/' | grep -A1 -xF "${PWD##*/}/" | tail -n 1)"'

# dragon-drop
alias \
	drag="dragon-drop" \
	drop="dragon-drop --target"

# eza -> l(a/l/h), tree
alias \
	l="eza --color=auto --group-directories-first" \
	ls="ls -hN --color=auto --group-directories-first" \
	la="eza -la --color=auto --group-directories-first" \
	ll="eza -l --color=auto --group-directories-first" \
	lh="eza -ld .?*" \
	tree="eza --tree"

# get & set clipboar
alias \
	setclip="xclip -sel clip" \
	getclip="xclip -out -sel clip"

# pacman
alias \
	pi="sudo pacman -S" \
	pu="sudo pacman -Syu"

#mutt
alias \
	mutt="neomutt" \
	upmutt="mbsync -a && neomutt"

#youtube-dl
alias \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt-dlp -f 'bestaudio[ext=m4a]' --embed-metadata" \
	ytt="yt-dlp --skip-download --write-thumbnail --embed-metadata" \
	ytv="yt-dlp -f 'bestvide[ext=mp4]+bestaudio[ext=m4a]'" \
	yta2c="yt-dlp --external-downloader aria2c --external-downloader-args '-j 16 -x 16 -s 16 -k 2M' -f 'bestaudio/best'" \
	ytv2c="yt-dlp --external-downloader aria2c --external-downloader-args '-j 16 -x 16 -s 16 -k 2M' -f 'bestvideo[height>=720]+bestaudio/best'"

alias \
	lf="lfub" \
	weather="curl wttr.in" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc"
    # gtkw="gtkwave -r XDG_CONFIG_HOME/gtkwave/.gtkwaverc"

	# weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
