#!/bin/sh

# starts one or multiple args in background
background() {
	for ((i=2;i<=$#;i++)); do
		${@[1]} ${@[$i]} &> /dev/null &|
	done
}

# Make dir and cd into it
mkcd() {
    mkdir -p "$1"
    cd "$1"
}

# cd and ls into dir
cl() {
	local dir="$1"
	local dir="${dir:=$HOME}"
	if [[ -d "$dir" ]]; then
		cd "$dir" >/dev/null; eza -la --color=auto --group-directories-first
	else
		echo "cl: $dir: Directory not found"
	fi
}

# haste
haste() {
    a=$(cat);
    curl -X POST -s -d "$a" https://paste.tiyn.eu/documents | awk -F '"' '{print "https://paste.tiyn.eu/"$4}';
}

# fzf
# TODO: what is this doing?
src() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
	;}
#src() { find ~/.config/* ~/.local/bin/* -type f | fzf | xargs -r $EDITOR ;}
srd() { find ~/cloud/* -type f | grep ".pdf" | fzf | xargs -r $READER ;}

# Search and install packages with yay and fzf
yi() {
    SELECTED_PKGS="$(yay -Slq | fzf --header='Install packages' -m --preview 'yay -Si {1}')"
    if [ -n "$SELECTED_PKGS" ]; then
        yay -S $(echo $SELECTED_PKGS)
    fi
}

# Search and remove packages with yay and fzf
yr() {
    SELECTED_PKGS="$(yay -Qsq | fzf --header='Remove packages' -m --preview 'yay -Si {1}')"
    if [ -n "$SELECTED_PKGS" ]; then
        yay -Runs $(echo $SELECTED_PKGS)
    fi
}

# yaya() { yay -Slq | fzf --reverse --prompt="yay install > " -q "$1" -m --preview 'yay -Si {1}'| xargs -ro yay -S }
# yayr() { yay -Qq | fzf --reverse --prompt="yay remove > " -q "$1" -m --preview 'yay -Qi {1}' | xargs -ro yay -Rns }
# yayu() { yay -Qqe | fzf --reverse --prompt="yay install > " -q "$1" -m --preview 'yay -Si {1}'| xargs -ro yay -Sy }

# cuebreakpoints
flacsplit() { cuebreakpoints $2 | shnsplit $1 -o flac }


