# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[└─>](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[directory]
style = 'bold green'

[git_branch]
style = 'bold blue'

[git_commit]
style = 'bold blue'
only_detached = false

[python]
style = 'bold green'

