#!/bin/sh

# required for using nextcloud
dbus-update-activation-environment --all
gnome-keyring-daemon --start --components=secrets

xset r rate 300 50 &                        # Speed xrate up
unclutter &                                 # Remove mouse when idle

dunst &                                     # dunst for notifications
dunstctl rule dnd_low disable &             # disable dnd for low urgencies
dunstctl rule dnd_normal disable &          # disable dnd for normal urgencies

redshift &                                  # redshift for saving your eyes
$STATUSBAR &                                # for refreshing the statusbar
syncthing &
discord &
keepassxc &
autorandr -c &                              # select monitor configuration
(sleep 10 ; pkill -RTMIN+4 $STATUSBAR) &    # reload volume section of statusbar
